// File generated by flutterfire_cli.
// For more information, see: https://github.com/firebase/flutterfire_cli
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Create a [FirebaseOptions] object by specifying the
/// Firebase project details in [fromMap] call below.
/// Alternatively, use the `FlutterFire CLI` to auto-generate Firebase
/// configuration files for your Flutter app. To do so, run:
///
/// ```bash
/// flutterfire configure
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForWeb', // Replace with your actual key
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'easy-reel-project', // Replace with your project ID
    authDomain: 'easy-reel-project.firebaseapp.com',
    databaseURL: 'https://easy-reel-project.firebaseio.com',
    storageBucket: 'easy-reel-project.appspot.com',
    measurementId: 'G-00000000',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClPQ_liY8UaGbb5C4z22eznNWufB1r_bg',
    appId: '1:1074266225348:android:a0281bf296502fcdd7e791',
    messagingSenderId: '1074266225348',
    projectId: 'easy-reel',
    storageBucket: 'easy-reel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLS1IojELJsG-7eI1pDDRT-Ebnv2ckN2Q',
    appId: '1:1074266225348:ios:ed08afedb22c771cd7e791',
    messagingSenderId: '1074266225348',
    projectId: 'easy-reel',
    storageBucket: 'easy-reel.firebasestorage.app',
    iosBundleId: 'com.example.easyReel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyFormacOS', // Replace with your actual key
    appId: '1:000000000000:macos:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'easy-reel-project', // Replace with your project ID
    databaseURL: 'https://easy-reel-project.firebaseio.com',
    storageBucket: 'easy-reel-project.appspot.com',
    iosBundleId: 'com.example.easyReel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForWindows', // Replace with your actual key
    appId: '1:000000000000:windows:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'easy-reel-project', // Replace with your project ID
    databaseURL: 'https://easy-reel-project.firebaseio.com',
    storageBucket: 'easy-reel-project.appspot.com',
    authDomain: 'easy-reel-project.firebaseapp.com',
  );
}