// File generated by flutterfire_cli.
// For more information, see: https://github.com/firebase/flutterfire_cli
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Create a [FirebaseOptions] object by specifying the
/// Firebase project details in [fromMap] call below.
/// Alternatively, use the `FlutterFire CLI` to auto-generate Firebase
/// configuration files for your Flutter app. To do so, run:
///
/// ```bash
/// flutterfire configure
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForWeb', // Replace with your actual key
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'easy-reel-project', // Replace with your project ID
    authDomain: 'easy-reel-project.firebaseapp.com',
    databaseURL: 'https://easy-reel-project.firebaseio.com',
    storageBucket: 'easy-reel-project.appspot.com',
    measurementId: 'G-00000000',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNPDpMI09fLz1AWUe-RYb1PbUGfQBOHa8',
    appId: '1:656720910751:android:9df45688327b5487e405aa',
    messagingSenderId: '656720910751',
    projectId: 'carrot-app-a2ad5',
    storageBucket: 'carrot-app-a2ad5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHh6pOAoPCmHOFlJ8LaAdYZFs3TAH1KT0',
    appId: '1:656720910751:ios:00a168ee86b5550ce405aa',
    messagingSenderId: '656720910751',
    projectId: 'carrot-app-a2ad5',
    storageBucket: 'carrot-app-a2ad5.firebasestorage.app',
    androidClientId: '656720910751-rp9ttsakf757b532gd0vlid6g69ck08f.apps.googleusercontent.com',
    iosClientId: '656720910751-gv6ruh6qgi3t657u01ct3bvd12pts84l.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyReel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyFormacOS', // Replace with your actual key
    appId: '1:000000000000:macos:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'easy-reel-project', // Replace with your project ID
    databaseURL: 'https://easy-reel-project.firebaseio.com',
    storageBucket: 'easy-reel-project.appspot.com',
    iosBundleId: 'com.example.easyReel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForWindows', // Replace with your actual key
    appId: '1:000000000000:windows:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'easy-reel-project', // Replace with your project ID
    databaseURL: 'https://easy-reel-project.firebaseio.com',
    storageBucket: 'easy-reel-project.appspot.com',
    authDomain: 'easy-reel-project.firebaseapp.com',
  );
}